name: tarea_mapa
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  http: ^1.1.0
  intl: ^0.18.1
  gradients: ^0.1.1+2
  geolocator: ^10.1.0
  url_launcher: ^6.2.1
  circular_menu: ^2.0.1
  google_maps_flutter: ^2.5.0
  path_provider: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
